version: '3.8'

services:
  app:
    build: 
      context: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secure-jwt-secret
      - DATA_FILE_PATH=/app/data/data.json
      - CORS_ORIGIN=*
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s